### ISSUE TITLE
UI defaults should be configurable outside of code

### ISSUE THREAD

**Issue by memory** [terabyte/stashbot#17]
Currently, UI defaults (for example the default build action, or whether emails are enabled) are configured by means of decorators inside JenkinsServerConfiguration.java, JobMapping.java, JobTypeStatusMapping.java, PullRequestMetadata.java and RepositoryConfiguration.java

As the "correct" default value is likely to be highly institution-dependent, these values should themselves be configurable via the UI.

**Comment by terabyte** [comment]
Agree completely.  This is low-priority for me but if someone wants to help out and implement this I would be glad to provide whatever help I can and I would definitely be willing to accept a PR.

A great first pass might be to replicate the repo config page somehow inside the jenkins config, that lets you make a "default" config whose values would be used for all new configs.  Unfortunately this is slightly circular since a repo config points to a jenkins config and a jenkins config would then point to a default repo config - repo config may need to be split up into a RepoConfig object which has (enabled, jenkins config) in it and a RepoSettings object which has all the things which may or may not have default values.
